=== AndroidOpenSourceSnda/android_vendor_st-ericsson/tools/platform/flash_kit/flash_tool_backend/com.stericsson.sdk.common.ui.config/ui_validator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:simpleType name="VisualType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TEXT_FIELD"></xs:enumeration>
			<xs:enumeration value="COMBO"></xs:enumeration>
			<xs:enumeration value="TEXT_FIELD_NO_EDIT"></xs:enumeration>
			<xs:enumeration value="PATH"></xs:enumeration>
			<xs:enumeration value="CHECK_BUTTON"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="profile">

		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="1">
				<xs:element name="section">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="record" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded" minOccurs="1">
										<xs:element name="attribute">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="visual">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="option" minOccurs="0" maxOccurs="unbounded">
																</xs:element>
															</xs:sequence>
															<xs:attribute name="label" type="xs:string">
															</xs:attribute>
															<xs:attribute name="regexpValidator" type="xs:string">
															</xs:attribute>
															<xs:attribute name="type" type="VisualType">
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string">
									</xs:attribute>
									<xs:attribute name="match" type="xs:string">
									</xs:attribute>
									<xs:attribute name="label" type="xs:string" use="optional">
									</xs:attribute>
									<xs:attribute name="minCount" type="xs:integer">
									</xs:attribute>
									<xs:attribute name="maxCount" type="xs:integer">
									</xs:attribute>
									<xs:attribute name="showGroup" type="xs:boolean">
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required">
						</xs:attribute>
						<xs:attribute name="extendable" type="xs:boolean" use="optional" default="false">
						</xs:attribute>
						<xs:attribute name="columns" type="xs:integer" use="optional" default="1">
						</xs:attribute>
						<xs:attribute name="columnSpan" type="xs:integer" use="optional" default="1">
						</xs:attribute>
						<xs:attribute name="layout" type="xs:string" use="optional" default="grid">
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="layout" type="xs:string" />
		</xs:complexType>


	</xs:element>




</xs:schema>

=== AndroidOpenSourceSnda/android_vendor_st-ericsson/tools/platform/flash_kit/flash_tool_backend/com.stericsson.sdk.common.ui.config/ui_mesp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<profile layout="grid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ui_validator.xsd">

	<section name="Configuration Settings" extendable="false" columns="1">
	
		<record match="Profile .*" minCount="1" maxCount="-1">
			<attribute name="alias">
				<visual label="Alias" type="TEXT_FIELD" regexpValidator="[a-zA-Z0-9_]+"/>				
			</attribute>
			<attribute name="path">
				<visual label="Path" type="PATH">
					<option label="*.prfl" value="*.prfl"/>
				</visual>
			</attribute>
		</record>
		
		<record match="ActiveProfile .*" minCount="1" maxCount="1">
			<attribute name="alias">
				<visual label="Alias" type="TEXT_FIELD" regexpValidator="[a-zA-Z0-9_]+" />
			</attribute>
		</record>
		
		<record match="USB .*" minCount="1" maxCount="1">
			<attribute name="enabled">
				<visual label="Enabled" type="CHECK_BUTTON">
					<option label="true" value="true"/>
					<option label="false" value="false"/>					
				</visual>
			</attribute>
		</record>
		
		<record match="UART .*" minCount="1" maxCount="1">
			<attribute name="alias">
				<visual label="Alias" type="TEXT_FIELD" regexpValidator="^[/a-zA-Z]+[a-zA-Z0-9]+"/>									
			</attribute>
			<attribute name="baudrate">
				<visual label="Baud Rate" type="COMBO">
					<option label="9600" value="9600"/>
					<option label="57600" value="57600"/>
					<option label="115200" value="115200"/>
					<option label="230400" value="230400"/>
					<option label="460800" value="460800"/>
					<option label="921600" value="921600"/>
				</visual>									
			</attribute>
			<attribute name="databits">
				<visual label="Data bits" type="COMBO">
					<option label="5" value="5"/>
					<option label="6" value="6"/>
					<option label="7" value="7"/>
					<option label="8" value="8"/>					
				</visual>
			</attribute>
			<attribute name="parity">
				<visual label="Parity" type="COMBO">
					<option label="Parity None" value="0"/>
					<option label="Parity Even" value="1"/>
					<option label="Parity Odd" value="2"/>
					<option label="Parity Mark" value="3"/>
					<option label="Parity Space" value="4"/>
    			</visual>									
			</attribute>
			<attribute name="stopbit">
				<visual label="Stop bits" type="COMBO">
					<option label="1" value="1"/>
					<option label="2" value="2"/>
				</visual>
			</attribute>
		</record>
		
		<record match="monitor .*" minCount="0" maxCount="1">
			<attribute name="acceptClients">
				<visual label="Accept Clients" type="CHECK_BUTTON">									
				</visual>
			</attribute>
			<attribute name="acceptEquipments">
				<visual label="Accept Equipments" type="CHECK_BUTTON">									
				</visual>
			</attribute>
		</record>
				        		        
	</section>

	
</profile>
