<?xml version="1.0"?>
<!-- The following DTD must not be included in every configuration file. It is only used when   -->
<!-- validating the XML document                                                                -->
<!DOCTYPE target_configuration [

    <!-- bax doctype configuration -->

    <!ELEMENT target_configuration                    	(bax:flash_archive?, bax:ram_image?)>
    <!ELEMENT bax:source                              	(#PCDATA)>  
    <!ELEMENT bax:flash_archive                       	(bax:entry*)>
	<!ELEMENT bax:ram_image								(bax:entry*)>
    <!ELEMENT bax:entry                               	(bax:source,bax:attribute*)>
    <!ELEMENT bax:attribute                         	(#PCDATA)>
    
    <!ATTLIST target_configuration      xmlns:bax       CDATA                                   	#FIXED "TBD">
    <!ATTLIST bax:entry                 name      		CDATA                         				#REQUIRED>
    <!ATTLIST bax:entry                 type      		CDATA										#REQUIRED>
    <!ATTLIST bax:attribute             name      		CDATA                         				#REQUIRED>
]>
<target_configuration>
	<bax:ram_image>
	    <bax:entry name="boot_image.bin" type="x-empflash/bootimage">
			<bax:source>boot_image</bax:source>
		</bax:entry>
		<bax:entry name="dntcert.bin" type="x-empflash/image">
			<bax:source>dntcert</bax:source>
			<bax:attribute name="TOC-ID">DNT-CERT</bax:attribute>
		</bax:entry>
		<bax:entry name="mem_init" type="x-empflash/image">
			<bax:source>mem_init</bax:source>
			<bax:attribute name="TOC-ID">MEM_INIT</bax:attribute>
		</bax:entry>
		<bax:entry name="power_management.bin" type="x-empflash/image">
			<bax:source>power_management</bax:source>
			<bax:attribute name="TOC-ID">PWR_MGT</bax:attribute>
		</bax:entry>

		<bax:entry name="ipl.bin" type="x-empflash/image">
			<bax:source>ipl</bax:source>
			<bax:attribute name="TOC-ID">IPL</bax:attribute>
		</bax:entry>

		<bax:entry name="modem.bin" type="x-empflash/image">
			<bax:source>modem</bax:source>
			<bax:attribute name="TOC-LoadAddress">0x06000000</bax:attribute>
			<bax:attribute name="TOC-ID">MODEM</bax:attribute>
		</bax:entry>

		<bax:entry name="normal" type="x-empflash/image">
			<bax:source>normal</bax:source>
			<bax:attribute name="TOC-ID">NORMAL</bax:attribute>
			<bax:attribute name="TOC-LoadAddress">0x00000000</bax:attribute>
			<bax:attribute name="TOC-EntryPoint">0x00000000</bax:attribute>
		</bax:entry>
	</bax:ram_image>
</target_configuration>

