=== AndroidOpenSourceSnda/android_vendor_st-ericsson/validation/hardware/tat/tat/DTDDynamicConfigurationFile.dtd
<!ELEMENT setup (menubar)>
<!ELEMENT menubar (menu*)>
<!ELEMENT menu (menu*) >
<!ATTLIST menu title CDATA #REQUIRED>
<!ATTLIST menu action CDATA #IMPLIED>
<!ATTLIST menu params CDATA #IMPLIED>

=== AndroidOpenSourceSnda/android_vendor_st-ericsson/validation/hardware/tat/tat/tatlvideo/config/menus/menu_09video.xml
<?xml version="1.0"?>
<!DOCTYPE setup SYSTEM "..\..\..\DTDDynamicConfigurationFile.dtd">

<setup>
	<menubar>
		<menu title="Visual">
			<menu title="Help" action="pdf" params="help/video.pdf"/>
		  <menu title="Camera">
		    <menu title="Static Configuration" action="exe" params="DTHAPP -c LINKTYPE IPADDRESS port=TCPPORT -v &quot;CAMERA STATIC TEST PANEL&quot; &quot;/DTH/VIDEO/config/panels/camera_static_conf.xml&quot;" />
		    <menu title="Dynamic Configuration" action="exe" params="DTHAPP -c LINKTYPE IPADDRESS port=TCPPORT -v &quot;CAMERA DYNAMIC TEST PANEL&quot; &quot;/DTH/VIDEO/config/panels/camera_dynamic_conf.xml&quot;" />
		  </menu>
		  <menu title="Display">
		    <menu title="LCD Main" action="exe" params="DTHAPP -c LINKTYPE IPADDRESS port=TCPPORT -v &quot;LCD MAIN TEST PANEL&quot; &quot;/DTH/VIDEO/config/panels/video_lcd_main.xml&quot;" />
		    <menu title="CVBS" action="exe" params="DTHAPP -c LINKTYPE IPADDRESS port=TCPPORT -v &quot;TVOut CVBS TEST PANEL&quot; &quot;/DTH/VIDEO/config/panels/video_extdisp_cvbs.xml&quot;" />
		    <menu title="HDMI" action="exe" params="DTHAPP -c LINKTYPE IPADDRESS port=TCPPORT -v &quot;TVOut HDMI TEST PANEL&quot; &quot;/DTH/VIDEO/config/panels/video_extdisp_hdmi.xml&quot;" />   
		  </menu>
	   </menu>
	</menubar>
</setup>
